services:
  reverse-proxy:
    image: httpd:latest
    ports:
      - "80:80"
      - "443:443"   # External access via HTTP redirects to HTTPS
    volumes:
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache2/conf/extra/reverse-proxy.conf:/usr/local/apache2/conf/extra/reverse-proxy.conf:ro
      - ./apache2/conf/extra/httpd-mod-ssl.conf:/usr/local/apache2/conf/extra/httpd-mod-ssl.conf:ro
      - ./apache2/conf/ssl:/usr/local/apache2/conf/ssl:ro
    depends_on:
      - todo-app
    networks:
      - public
      - internal

  todo-app-frontend:
    image: eneabette/taskmanager-demo-frontend:latest
    container_name: todo-app-frontend
    depends_on:
      - todo-app
    environment:
      API_BASE_URL: ${API_BASE_URL}
    networks:
      - internal
    # No published ports – accessible only via Docker networking

  todo-app:
    build:
      context: ../
      dockerfile: Dockerfile
    image: eneabette/taskmanager-demo-backend:latest
    container_name: todo-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - postgresql
    networks:
      - internal
    # No published ports – accessible only via Docker networking

  postgresql:
    image: postgres:latest
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
      - ./postgres/sql/import.sql:/docker-entrypoint-initdb.d/import.sql:ro
    networks:
      - internal
    # No published ports – accessible only within the network

networks:
  internal:
    driver: bridge
  public:
    driver: bridge

volumes:
    pgdata: